name: flutter_gemini
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3
  hive: ^2.2.3
  http: ^1.2.2
  win32: ^5.6.0
  provider: ^6.1.2
  flutter_tts: ^4.0.2
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_sound: ^9.16.3
  flutter_dotenv: ^5.1.0
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  flutter_markdown: ^0.6.21
  connectivity_plus: ^6.0.5
  permission_handler: ^11.3.1
  google_generative_ai: ^0.2.2
  font_awesome_flutter: ^10.7.0
  sensors_plus: ^6.1.0
  snake: ^0.1.0
  fl_chart: ^0.69.0
  mobile_scanner: ^6.0.1
  geolocator: ^13.0.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
